name: family-tree-roots
services:
- name: web
  environment_slug: php
  instance_size_slug: basic-xxs    # This matches your 1GB/1vCPU spec
  github:
    branch: main
    deploy_on_push: true
  run_command: heroku-php-apache2 -F fpm_custom.conf -i php_custom.ini public/
  build_command: |
    composer install --no-dev --optimize-autoloader --prefer-dist --no-scripts
    composer dump-autoload -o
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    npm install --production && npm run build
  envs:
  - key: PHP_MEMORY_LIMIT
    value: "256M"
  - key: PHP_MAX_EXECUTION_TIME
    value: "30"
  - key: FPM_MAX_CHILDREN
    value: "3"
  - key: APP_NAME
    value: "Your App Name"
  - key: APP_ENV
    value: "production"
  - key: APP_DEBUG
    value: "false"
  - key: APP_URL
    value: ${APP_URL}
  - key: APP_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${APP_KEY}
  - key: LIVEWIRE_ASSET_URL
    value: ${APP_URL}
  - key: MEDIA_DISK
    value: "s3"  # For Spatie Media Library
  - key: QUEUE_CONNECTION
    value: "database"  # Or "redis" if you prefer
  - key: CACHE_DRIVER
    value: "redis"
  - key: SESSION_DRIVER
    value: "redis"
  - key: FILESYSTEM_DISK
    value: "do"  # For Digital Ocean Spaces